<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "resultify_message_box"
 *
 * Auto generated by Extension Builder 2017-10-09
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Message Box',
    'description' => 'Adds possibility to show message boxes (notifications) to FE users.',
    'category' => 'misc',
    'author' => 'Alex',
    'author_email' => 'alex@pixelant.se',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
